name: conic-survey
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - ld_impl_linux-64=2.40
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgomp=12.2.0
  - libnsl=2.0.0
  - libsqlite=3.40.0
  - libuuid=2.32.1
  - libzlib=1.2.13
  - ncurses=6.3
  - openssl=3.1.0
  - pip=23.0.1
  - python=3.9.16
  - readline=8.1.2
  - tk=8.6.12
  - tzdata=2022g
  - wheel=0.40.0
  - xz=5.2.6
  - pip:
    - absl-py==1.4.0
    - addict==2.4.0
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - albumentations==1.3.0
    - aliyun-python-sdk-core==2.14.0
    - aliyun-python-sdk-kms==2.16.2
    - asttokens==2.2.1
    - async-timeout==4.0.2
    - attrs==22.2.0
    - backcall==0.2.0
    - cachetools==5.3.0
    - certifi==2022.12.7
    - cffi==1.16.0
    - charset-normalizer==3.1.0
    - click==8.1.7
    - cmake==3.25.0
    - colorama==0.4.6
    - comm==0.1.3
    - contourpy==1.0.7
    - crcmod==1.7
    - cryptography==41.0.5
    - cycler==0.11.0
    - datasets==2.10.1
    - debugpy==1.6.7
    - decorator==5.1.1
    - dill==0.3.6
    - docopt==0.6.2
    - et-xmlfile==1.1.0
    - evaluate==0.4.0
    - executing==1.2.0
    - filelock==3.9.0
    - fonttools==4.39.2
    - frozenlist==1.3.3
    - fsspec==2023.3.0
    - google-auth==2.16.2
    - google-auth-oauthlib==0.4.6
    - grpcio==1.51.3
    - h5py==3.8.0
    - huggingface-hub==0.13.3
    - idna==3.4
    - imageio==2.26.1
    - importlib-metadata==6.8.0
    - importlib-resources==5.12.0
    - ipykernel==6.22.0
    - ipython==8.12.0
    - jedi==0.18.2
    - jinja2==3.1.2
    - jmespath==0.10.0
    - joblib==1.2.0
    - jupyter-client==8.1.0
    - jupyter-core==5.3.0
    - kiwisolver==1.4.4
    - lazy-loader==0.1
    - lit==15.0.7
    - markdown==3.4.1
    - markdown-it-py==3.0.0
    - markupsafe==2.1.2
    - matplotlib==3.7.1
    - matplotlib-inline==0.1.6
    - mdurl==0.1.2
    - mmcv==2.1.0
    - mmcv-full==1.7.1
    - mmdet==3.2.0
    - mmengine==0.9.1
    - model-index==0.1.11
    - mpmath==1.2.1
    - multidict==6.0.4
    - multiprocess==0.70.14
    - nest-asyncio==1.5.6
    - networkx==3.0
    - numpy==1.24.2
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - oauthlib==3.2.2
    - opencv-python==4.8.1.78
    - opencv-python-headless==4.7.0.72
    - opendatalab==0.0.10
    - openmim==0.3.9
    - openpyxl==3.1.2
    - openxlab==0.0.28
    - ordered-set==4.1.0
    - oss2==2.17.0
    - packaging==23.0
    - pandas==1.5.3
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.3.0
    - platformdirs==4.0.0
    - prompt-toolkit==3.0.38
    - protobuf==3.20.3
    - psutil==5.9.4
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyarrow==11.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycocotools==2.0.6
    - pycparser==2.21
    - pycryptodome==3.19.0
    - pygments==2.14.0
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytz==2023.3.post1
    - pywavelets==1.4.1
    - pyyaml==6.0
    - pyzmq==25.0.2
    - qudida==0.0.4
    - regex==2022.10.31
    - requests==2.28.2
    - requests-oauthlib==1.3.1
    - responses==0.18.0
    - rich==13.4.2
    - rsa==4.9
    - scikit-image==0.20.0
    - scikit-learn==1.2.2
    - scipy==1.9.1
    - seaborn==0.12.2
    - setuptools==60.2.0
    - shapely==2.0.2
    - six==1.16.0
    - stack-data==0.6.2
    - sympy==1.11.1
    - tabulate==0.9.0
    - tensorboard==2.12.0
    - tensorboard-data-server==0.7.0
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.6
    - termcolor==2.3.0
    - terminaltables==3.1.10
    - threadpoolctl==3.1.0
    - tifffile==2023.3.15
    - tokenizers==0.13.2
    - tomli==2.0.1
    - torch==2.0.0
    - torch-geometric==2.3.0
    - torchaudio==2.0.1
    - torchmetrics==0.11.4
    - torchsummary==1.5.1
    - torchvision==0.15.1
    - tornado==6.2
    - tqdm==4.65.0
    - traitlets==5.9.0
    - transformers==4.27.1
    - triton==2.0.0
    - typing-extensions==4.4.0
    - urllib3==1.26.15
    - wcwidth==0.2.6
    - werkzeug==2.2.3
    - xxhash==3.2.0
    - yapf==0.40.2
    - yarl==1.8.2
    - zipp==3.15.0
